GnuCash-Pocket/gnucash-android

app/build.gradle
app/proguard-project.txt
app/proguard-rules.pro
app/src/androidTest/java/org/gnucash/android/test/ui/AccountsActivityTest.java
app/src/androidTest/java/org/gnucash/android/test/ui/CalculatorEditTextTest.java
app/src/androidTest/java/org/gnucash/android/test/ui/ExportTransactionsTest.java
app/src/androidTest/java/org/gnucash/android/test/ui/FirstRunWizardActivityTest.java
app/src/androidTest/java/org/gnucash/android/test/ui/MultiBookTest.java
app/src/androidTest/java/org/gnucash/android/test/ui/OwnCloudExportTest.java
app/src/androidTest/java/org/gnucash/android/test/ui/PieChartReportTest.java
app/src/androidTest/java/org/gnucash/android/test/ui/TransactionsActivityTest.java
app/src/androidTest/java/org/gnucash/android/test/ui/util/DisableAnimationsRule.java
app/src/debug/AndroidManifest.xml
app/src/main/java/org/gnucash/android/app/GnuCashApplication.java
app/src/main/java/org/gnucash/android/db/MigrationHelper.java
app/src/main/java/org/gnucash/android/util/BackupManager.java
app/src/main/res/menu/global_actions.xml

All the com.android.support libs were replaced by their androidx counterparts and had their versions bumped up.
Deprecated `androidx.test.runner.AndroidJUnit4` is replaced by `androidx.test.ext.junit.runners.AndroidJUnit4` (which now belongs in a separate lib).
Animation scale can no longer be set by `mSetAnimationScalesMethod = windowManagerClazz.getDeclaredMethod("setAnimationScales", float[].class);`, as this method is not present in newer APIs (`android.permission.SET_ANIMATION_SCALE` itself is now a protected permission, restricted to system processes). Instead, `UiAutomation.executeShellCommand(command)` is used for this purpose, with the required permission acquired by UiAutomator at the moment they are needed.
There are still broken tests (wip), but this PR fixes a few of them.

Update com.android.support libs to androidx. Update test dependencies.

---

app/src/androidTest/java/org/gnucash/android/test/ui/CalculatorEditTextTest.java
app/src/androidTest/java/org/gnucash/android/test/ui/util/SoftwareKeyboard.java
app/src/main/java/org/gnucash/android/ui/export/ExportFormFragment.java
app/src/main/java/org/gnucash/android/ui/transaction/TransactionFormFragment.java
app/src/main/res/layout/fragment_transaction_form.xml

Replace the old CalculatorKeyboard in transaction_form by a regular software keyboard and set the `inputType` of transaction amount edit text to `numberDecimal`. 
|Before|After|
|---|---|
| ![Screenshot_1685397664](https://github.com/GnuCash-Pocket/gnucash-android/assets/316087/7d1eea05-435e-4a95-be6f-c24fcf22ed15) | ![Screenshot_1685397639](https://github.com/GnuCash-Pocket/gnucash-android/assets/316087/4cf16cb7-23bb-4934-8214-8cfb48e682a1) |

Remove software keyboard from fragment_transaction_form.xml.

---

app/src/androidTest/java/org/gnucash/android/test/ui/TransactionsActivityTest.java

Some other test sometimes leaves one transaction in the account referred by TRANSACTIONS_ACCOUNT_UID, probably during the cleanup phase. While clearing the transactions at the beginning of testAddMultiCurrencyTransaction() might not be the ideal solution, that's the shortest one I could find that consistently fixes this legacy test. I don't want to touch any other passing tests and possibly introduce further bugs in them.
I'm convinced this change fixes Issue https://github.com/GnuCash-Pocket/gnucash-android/issues/26.

Cleanup all transactions at beginning of TransactionsActivityTest.testAddMultiCurrencyTransaction()

---

app/src/main/java/org/gnucash/android/export/csv/CsvTransactionsExporter.java

Fix date format (from "week year" to "year") so that last/first days of year don't get a wrong year when exporting (Issue #33)
Based on thatsokay's PR https://github.com/codinguser/gnucash-android/pull/904/commits/fea03d3d6af0c9f1fb3083080388742ae73c38fa. He also removed the trailing delimiter at the end of the heading row, but I'm not good in Java and am not sure if I break sth.

fix date format in CSV export

---

app/src/main/res/layout/activity_transaction_detail.xml

No margin for right-aligned title in transaction details screen.

Fix issue #790 - text margins for RTL text in transaction details screen.

---

app/src/main/java/org/gnucash/android/util/BackupManager.java

There was an issue with nextcloud/ownCloud when backup book:
```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.owncloud.android.datamodel.OCFile.existsOnDevice()' on a null object reference
at android.os.Parcel.createExceptionOrNull(Parcel.java:3017)
at android.os.Parcel.createException(Parcel.java:2995)
at android.os.Parcel.readException(Parcel.java:2978)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:705)
at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1862)
at …
```

Backup each book

---

app/src/main/java/org/gnucash/android/export/ExportAsyncTask.java
app/src/main/java/org/gnucash/android/importer/ImportAsyncTask.java
app/src/main/java/org/gnucash/android/ui/settings/dialog/DoubleConfirmationDialog.java
app/src/main/java/org/gnucash/android/util/BackupManager.java

```
Fatal Exception: java.lang.IllegalArgumentException: View=DecorView@d34449b[Exporting transactions] not attached to window manager
at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:657)
at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:564)
at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:208)
at android.app.Dialog.dismissDialog(Dialog.java:801)
at android.app.Dialog.dismiss(Dialog.java:783)
at org.gnucash.android.export.ExportAsyncTask.dismissProgressDialog(ExportAsyncTask.java:205)
at org.gnucash.android.export.ExportAsyncTask.onPostExecute(ExportAsyncTask.java:186)
at org.gnucash.android.export.ExportAsyncTask.onPostExecute(ExportAsyncTask.java:89)
at android.os.AsyncTask.finish(AsyncTask.java:771)
at …
```

Progress dialog can cancel.

---

app/build.gradle

Google Play store complains about missing language "gr".
https://stackoverflow.com/questions/57859122/invalid-splitapkbundle-the-bundle-targets-unknown-languages-gr-google-play

Disable bundle split for languages.

---

app/src/main/java/org/gnucash/android/export/ExportAsyncTask.java
app/src/main/java/org/gnucash/android/importer/ImportAsyncTask.java
app/src/main/java/org/gnucash/android/ui/export/ExportFormFragment.java
app/src/main/java/org/gnucash/android/ui/settings/AccountPreferencesFragment.java

```
Caused by java.lang.SecurityException: Permission Denial: opening provider com.google.android.apps.docs.common.storagebackend.StorageBackendContentProvider from ProcessRecord{418982b 18195:org.gnucash.pocket.pnemonic/u0a280} (pid=18195, uid=10280) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
at android.os.Parcel.createExceptionOrNull(Parcel.java:3182)
at android.os.Parcel.createException(Parcel.java:3166)
at android.os.Parcel.readException(Parcel.java:3149)
at android.os.Parcel.readException(Parcel.java:3091)
at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:6006)
at android.app.ActivityThread.acquireProvider(ActivityThread.java:7637)
at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl …
```

Manage documents permission

---

app/src/main/java/org/gnucash/android/ui/util/widget/CalculatorEditText.java

In #92  an error was introduced, which instantiated the AppCompatEditText with the defStyleAttr value of zero. This broke the edit text view, which led to crashes if the calculator keyboard was used.

fix broken split transaction fragment

---

app/src/main/java/org/gnucash/android/ui/transaction/ScheduledActionsListFragment.java
app/src/main/java/org/gnucash/android/ui/transaction/TransactionsListFragment.java

Looks very strange when the secondary label is blank.

Does the transaction have some problem?

---

app/src/main/java/org/gnucash/android/db/DatabaseHelper.java
app/src/main/java/org/gnucash/android/db/adapter/TransactionsDbAdapter.java
app/src/main/java/org/gnucash/android/ui/account/AccountsListFragment.java

Sort the filtered transactions by timestamp.

---

app/src/main/java/org/gnucash/android/ui/report/barchart/StackedBarChartFragment.java

```
Caused by java.lang.IllegalArgumentException: colors array and labels array need to be of same size
at com.github.mikephil.charting.components.Legend.setCustom(Legend.java:322)
at org.gnucash.android.ui.report.barchart.StackedBarChartFragment.setCustomLegend(StackedBarChartFragment.java:334)
at org.gnucash.android.ui.report.barchart.StackedBarChartFragment.generateReport(StackedBarChartFragment.java:302)
at org.gnucash.android.ui.report.BaseReportFragment$1.doInBackground(BaseReportFragment.java:297)
at org.gnucash.android.ui.report.BaseReportFragment$1.doInBackground(BaseReportFragment.java:288)
at android.os.AsyncTask$3.call(AsyncTask.java:378)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
at …
```

"colors array and labels array need to be of same size"

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/org/gnucash/android/export/DropboxHelper.java
app/src/main/java/org/gnucash/android/export/ExportAsyncTask.java
app/src/main/java/org/gnucash/android/ui/export/ExportFormFragment.java
app/src/main/java/org/gnucash/android/ui/settings/BackupPreferenceFragment.java

```
Caused by java.lang.NullPointerException: accessToken
at com.dropbox.core.v2.DbxClientV2$DbxUserRawClientV2.<init>(DbxClientV2.java:70)
at com.dropbox.core.v2.DbxClientV2.<init>(DbxClientV2.java:47)
at com.dropbox.core.v2.DbxClientV2.<init>(DbxClientV2.java:31)
at org.gnucash.android.export.DropboxHelper.getClient(DropboxHelper.java:82)
at org.gnucash.android.export.ExportAsyncTask.moveExportToDropbox(ExportAsyncTask.java:363)
at org.gnucash.android.export.ExportAsyncTask.moveToTarget(ExportAsyncTask.java:254)
at org.gnucash.android.export.ExportAsyncTask.doInBackground(ExportAsyncTask.java:159)
at org.gnucash.android.export.ExportAsyncTask.doInBackground(ExportAsyncTask.java:90)
at android.os.AsyncTask$3.call(AsyncTask.java:394)
at …
```

Dropbox access tokens empty?

---

app/src/main/java/org/gnucash/android/ui/transaction/dialog/TransferFundsDialogFragment.java
app/src/main/kotlin/org/gnucash/android/model/Price.kt

```
Fatal Exception: android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY[787])
at android.database.sqlite.SQLiteConnection.nativeExecute(SQLiteConnection.java)
at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:1034)
at android.database.sqlite.SQLiteSession.execute(SQLiteSession.java:621)
at android.database.sqlite.SQLiteStatement.execute(SQLiteStatement.java:47)
at org.gnucash.android.db.adapter.DatabaseAdapter.addRecord(DatabaseAdapter.java:244)
at org.gnucash.android.db.adapter.DatabaseAdapter.addRecord(DatabaseAdapter.java:215)
at org.gnucash.android.ui.transaction.dialog.TransferFundsDialogFragment.transferFunds(TransferFundsDialogFragment.java:224)
at …
```

Avoid "FOREIGN KEY constraint failed" for price.

---

app/src/main/java/org/gnucash/android/db/adapter/CommoditiesDbAdapter.java
app/src/main/java/org/gnucash/android/ui/transaction/dialog/TransferFundsDialogFragment.java

```
Fatal Exception: android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY[787])
at android.database.sqlite.SQLiteConnection.nativeExecute(SQLiteConnection.java)
at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:1034)
at android.database.sqlite.SQLiteSession.execute(SQLiteSession.java:621)
at android.database.sqlite.SQLiteStatement.execute(SQLiteStatement.java:47)
at org.gnucash.android.db.adapter.DatabaseAdapter.addRecord(DatabaseAdapter.java:232)
at org.gnucash.android.ui.transaction.dialog.TransferFundsDialogFragment.transferFunds(TransferFundsDialogFragment.java:228)
at org.gnucash.android.ui.transaction.dialog.TransferFundsDialogFragment.-$$Nest$mtransferFunds()
at …
```

Cannot add price if commodities not in database.

---

app/src/main/java/org/gnucash/android/ui/account/AccountsListFragment.java
app/src/main/java/org/gnucash/android/ui/budget/BudgetListFragment.java
app/src/main/java/org/gnucash/android/ui/settings/BookManagerFragment.java
app/src/main/java/org/gnucash/android/ui/transaction/ScheduledActionsListFragment.java
app/src/main/java/org/gnucash/android/ui/transaction/TransactionsListFragment.java

```
Fatal Exception: java.lang.IllegalStateException: Can't access ViewModels from detached fragment
at androidx.fragment.app.Fragment.getViewModelStore(Fragment.java:414)
at androidx.loader.app.LoaderManager.getInstance(LoaderManager.java:128)
at androidx.fragment.app.Fragment.getLoaderManager(Fragment.java:1425)
at org.gnucash.android.ui.account.AccountsListFragment.refresh(AccountsListFragment.java:319)
at org.gnucash.android.ui.account.AccountsListFragment.lambda$tryDeleteAccount$0(AccountsListFragment.java:261)
at org.gnucash.android.ui.account.AccountsListFragment.$r8$lambda$rXxyQAMaXqiegwYU5GZCPqetBfY()
at org.gnucash.android.ui.account.AccountsListFragment$$ExternalSyntheticLambda0.invoke(D8$$SyntheticClass)
at org.gnucash.android.util.BackupManager$1.onPostExecute(BackupManager.ja …
```

Can reload list when fragment attached.

---

app/src/main/java/org/gnucash/android/ui/wizard/FirstRunWizardActivity.java

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void com.tech.freak.wizardpager.model.Page.resetData(android.os.Bundle)' on a null object reference
at com.tech.freak.wizardpager.model.AbstractWizardModel.load(AbstractWizardModel.java:71)
at org.gnucash.android.ui.wizard.FirstRunWizardActivity.createWizardModel(FirstRunWizardActivity.java:146)
at org.gnucash.android.ui.wizard.FirstRunWizardActivity.onCreate(FirstRunWizardActivity.java:85)
at android.app.Activity.performCreate(Activity.java:8290)
at android.app.Activity.performCreate(Activity.java:8270)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4085)
at …
```

Was first run wizard model changed?

---

app/build.gradle
app/src/androidTest/java/org/gnucash/android/test/ui/TransactionsActivityTest.java
app/src/main/java/org/gnucash/android/db/adapter/AccountsDbAdapter.java
app/src/main/java/org/gnucash/android/export/ExportAsyncTask.java
app/src/main/java/org/gnucash/android/export/qif/QifExporter.java
app/src/main/java/org/gnucash/android/export/xml/GncXmlExporter.java
app/src/main/java/org/gnucash/android/ui/homescreen/WidgetConfigurationActivity.java
app/src/main/java/org/gnucash/android/ui/transaction/TransactionFormFragment.java
app/src/main/java/org/gnucash/android/ui/transaction/dialog/TransferFundsDialogFragment.java
app/src/main/java/org/gnucash/android/ui/util/TextInputResetError.kt
app/src/main/kotlin/org/gnucash/android/export/ofx/OfxExporter.kt
app/src/main/kotlin/org/gnucash/android/model/Commodity.kt
app/src/main/kotlin/org/gnucash/android/model/Money.kt
app/src/main/kotlin/org/gnucash/android/model/Price.kt
app/src/main/res/layout/dialog_transfer_funds.xml
app/src/test/java/org/gnucash/android/test/unit/GnuCashTest.kt
app/src/test/java/org/gnucash/android/test/unit/db/AccountsDbAdapterTest.java
app/src/test/java/org/gnucash/android/test/unit/model/MoneyTest.java
app/src/test/java/org/gnucash/android/test/unit/model/PriceTest.java

Fixes issue #98 for the QIF export.
```
org.gnucash.android.export.Exporter$ExporterException: Failed to generate export with parameters: Export all transactions created since 2025-01-01 12:32:31.917 UTC as QIF to SHARING - split quantity has illegal denominator: 100000000
at org.gnucash.android.export.qif.QifExporter.generateExport(QifExporter.java:222)
at org.gnucash.android.export.ExportAsyncTask.doInBackground(ExportAsyncTask.java:135)
at org.gnucash.android.export.ExportAsyncTask.doInBackground(ExportAsyncTask.java:87)
```

QIF export denomination

---

app/src/main/java/org/gnucash/android/ui/budget/BudgetFormFragment.java
app/src/main/java/org/gnucash/android/ui/export/ExportFormFragment.java

```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=5; index=-1
at com.codetroopers.betterpickers.recurrencepicker.EventRecurrenceFormatter.getRepeatString(EventRecurrenceFormatter.java:113)
at org.gnucash.android.ui.export.ExportFormFragment.onRecurrenceSet(ExportFormFragment.java:598)
at com.codetroopers.betterpickers.recurrencepicker.RecurrencePickerDialogFragment.onClick(RecurrencePickerDialogFragment.java:1262)
at android.view.View.performClick(View.java:8033)
at android.view.View.performClickInternal(View.java:8010)
at android.view.View.-$$Nest$mperformClickInternal()
at android.view.View$PerformClick.run(View.java:31336)
at android.os.Handler.handleCallback(Handler.java:991)
at android.os.Handler.dispatchMessage(Handler.java:102)
at …
```

Ignore bad recurrence.

---

app/src/main/java/org/gnucash/android/db/adapter/AccountsDbAdapter.java
app/src/main/java/org/gnucash/android/db/adapter/DatabaseAdapter.java
app/src/main/java/org/gnucash/android/ui/account/AccountsListFragment.java

```
Fatal Exception: java.lang.IllegalArgumentException: accounts with GUID 10223989ddcabf496a16f5b4c390b4e1 does not exist in the db
at org.gnucash.android.db.adapter.DatabaseAdapter.getID(DatabaseAdapter.java:577)
at org.gnucash.android.db.adapter.DatabaseAdapter.deleteRecord(DatabaseAdapter.java:759)
at org.gnucash.android.db.adapter.AccountsDbAdapter.deleteRecord(AccountsDbAdapter.java:1355)
at org.gnucash.android.ui.account.AccountsListFragment.lambda$tryDeleteAccount$0(AccountsListFragment.java:262)
at org.gnucash.android.ui.account.AccountsListFragment.$r8$lambda$rXxyQAMaXqiegwYU5GZCPqetBfY()
at org.gnucash.android.ui.account.AccountsListFragment$$ExternalSyntheticLambda0.invoke(D8$$SyntheticClass)
at org.gnucash.android.util.BackupManager$1.onPostExecute(BackupManager.java:252)
at …
```

Reduce "Record does not exist in the db"

---

app/src/main/java/org/gnucash/android/db/adapter/AccountsDbAdapter.java
app/src/main/java/org/gnucash/android/db/adapter/DatabaseAdapter.java
app/src/main/java/org/gnucash/android/export/csv/CsvTransactionsExporter.kt
app/src/main/java/org/gnucash/android/service/ScheduledActionService.java
app/src/main/java/org/gnucash/android/ui/transaction/TransactionsActivity.java

```
Caused by java.lang.IllegalArgumentException: the bind value at index 1 is null
at android.database.sqlite.SQLiteProgram.bindString(SQLiteProgram.java:168)
at android.database.sqlite.SQLiteProgram.bindAllArgsAsStrings(SQLiteProgram.java:204)
at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:49)
at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1712)
at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1559)
at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1430)
at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1598)
at org.gnucash.android.db.adapter.DatabaseAdapter.fetchRecord(DatabaseAdapter.java:514)
at …
```

Record for UID is null?

---

app/src/main/java/org/gnucash/android/db/adapter/SplitsDbAdapter.java
app/src/main/java/org/gnucash/android/ui/account/DeleteAccountDialogFragment.java

```
Fatal Exception: android.database.sqlite.SQLiteConstraintException: NOT NULL constraint failed: splits.account_uid (code 1299 SQLITE_CONSTRAINT_NOTNULL)
at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(SQLiteConnection.java)
at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:913)
at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:756)
at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:67)
at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1975)
at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1921)
at org.gnucash.android.db.adapter.DatabaseAdapter.updateRecords(DatabaseAdapter.java:759)
at …
```

Move splits for valid account.

---

app/src/main/java/org/gnucash/android/ui/account/AccountFormFragment.java
app/src/main/java/org/gnucash/android/ui/budget/BudgetFormFragment.java

```
Fatal Exception: android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY)
at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(SQLiteConnection.java)
at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:961)
at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:89)
at org.gnucash.android.db.adapter.DatabaseAdapter.addRecord(DatabaseAdapter.java:225)
at org.gnucash.android.db.adapter.AccountsDbAdapter.addRecord(AccountsDbAdapter.java:184)
at org.gnucash.android.ui.account.AccountFormFragment.saveAccount(AccountFormFragment.java:672)
at …
```

Account with selected commodity.

---

app/src/main/java/org/gnucash/android/db/adapter/DatabaseAdapter.java

```
Fatal Exception: java.lang.IllegalArgumentException: Record not found in transactions
at org.gnucash.android.db.adapter.DatabaseAdapter.getID(DatabaseAdapter.java:658)
at org.gnucash.android.db.adapter.DatabaseAdapter.deleteRecord(DatabaseAdapter.java:784)
at org.gnucash.android.ui.transaction.ScheduledTransactionsViewHolder.deleteSchedule(ScheduledTransactionsViewHolder.kt:88)
at org.gnucash.android.ui.transaction.ScheduledViewHolder.onMenuItemClick$lambda$1(ScheduledViewHolder.kt:73)
at org.gnucash.android.ui.transaction.ScheduledViewHolder.$r8$lambda$_epRRWydNWXXzU2HI7NsG3mlQK8()
at org.gnucash.android.ui.transaction.ScheduledViewHolder$$ExternalSyntheticLambda0.invoke(D8$$SyntheticClass)
at org.gnucash.android.util.BackupManager$1.onPostExecute(BackupManager.java:248)
at …
```

Record not found in transactions

---

app/src/main/java/org/gnucash/android/ui/common/FormActivity.java

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
at java.lang.Enum.valueOf(Enum.java:252)
at org.gnucash.android.ui.common.FormActivity$FormType.valueOf(FormActivity.java:57)
at org.gnucash.android.ui.common.FormActivity.onCreate(FormActivity.java:100)
at android.app.Activity.performCreate(Activity.java:7994)
at android.app.Activity.performCreate(Activity.java:7978)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1548)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3406)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3607)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) …
```

Form type required

---

app/src/main/java/org/gnucash/android/ui/transaction/TransactionFormFragment.java

```
23:41:16.861  E  android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5 SQLITE_BUSY)
at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:757)
at android.database.sqlite.SQLiteSession.beginTransactionUnchecked(SQLiteSession.java:336)
at android.database.sqlite.SQLiteSession.beginTransaction(SQLiteSession.java:311)
at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:819)
at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:802)
at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:653)
at org.gnucash.android.db.adapter.DatabaseAdapter.beginTransaction(DatabaseAdapter.java:878)
at …
```

database is locked?
