GnuCash-Pocket/gnucash-android

.github/workflows/ci-build.yml

Create rudimentary CI Pipeline

---

.github/workflows/nightly-build.yml

create nightly build

---

README.md

from travis-ci to github actions workflows

Update Status Badge

---

app/src/main/res/layout/activity_budgets.xml
app/src/main/res/layout/activity_transaction_detail.xml

Transaction details screen - edit icon centered in floating button

Transaction details screen - edit icon centered in floating button

---

app/src/main/java/org/gnucash/android/db/adapter/BooksDbAdapter.java
app/src/main/java/org/gnucash/android/db/adapter/DatabaseAdapter.java

```
Caused by java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.get(ArrayList.java:437)
at org.gnucash.android.db.adapter.BooksDbAdapter.setFirstBookAsActive(BooksDbAdapter.java:248)
at org.gnucash.android.db.adapter.BooksDbAdapter.fixBooksDatabase(BooksDbAdapter.java:212)
at org.gnucash.android.app.GnuCashApplication.initializeDatabaseAdapters(GnuCashApplication.java:164)
at org.gnucash.android.app.GnuCashApplication.onCreate(GnuCashApplication.java:139)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6859)
at android.app.ActivityThread.access$1300(ActivityThread.java:268)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1982)
at …
```

Avoid "IndexOutOfBoundsException: Index: 0, Size: 0"

---

app/src/main/java/org/gnucash/android/ui/account/AccountFormFragment.java
app/src/main/java/org/gnucash/android/ui/account/AccountsListFragment.java
app/src/main/java/org/gnucash/android/ui/account/DeleteAccountDialogFragment.java
app/src/main/java/org/gnucash/android/ui/colorpicker/ColorPickerDialog.java
app/src/main/java/org/gnucash/android/ui/common/Refreshable.java
app/src/main/java/org/gnucash/android/ui/settings/BookManagerFragment.java
app/src/main/java/org/gnucash/android/ui/settings/dialog/DeleteBookConfirmationDialog.java
app/src/main/java/org/gnucash/android/ui/transaction/TransactionsListFragment.java
app/src/main/java/org/gnucash/android/ui/transaction/dialog/BulkMoveDialogFragment.java
app/src/main/java/org/gnucash/android/ui/transaction/dialog/TransactionsDeleteConfirmationDialogFragment.java

getTargetFragment is deprecated and was sometimes causing null-pointer-exception

Fragment result listener instead of target fragment.

---

app/src/main/java/org/gnucash/android/export/xml/GncXmlExporter.java
app/src/main/java/org/gnucash/android/export/xml/GncXmlHelper.java
app/src/main/kotlin/org/gnucash/android/model/ScheduledAction.kt
app/src/test/java/org/gnucash/android/test/unit/export/GncXmlHelperTest.java

https://bugs.openjdk.org/browse/JDK-6231579

Synchronize date formatter.

---

app/src/androidTest/java/org/gnucash/android/test/ui/CalculatorEditTextTest.java
app/src/main/java/org/gnucash/android/ui/transaction/SplitEditorFragment.java
app/src/main/java/org/gnucash/android/ui/transaction/TransactionFormFragment.java
app/src/main/java/org/gnucash/android/ui/util/widget/CalculatorEditText.java
app/src/main/java/org/gnucash/android/util/AmountParser.java

```
Non-fatal Exception: java.text.ParseException: Parse error
at org.gnucash.android.util.AmountParser.parse(AmountParser.java:28)
at org.gnucash.android.ui.util.widget.CalculatorEditText.getValue(CalculatorEditText.java:319)
at org.gnucash.android.ui.util.widget.TransactionTypeSwitch$OnTypeChangedListener.onCheckedChanged(TransactionTypeSwitch.java:187)
at android.widget.CompoundButton.setChecked(CompoundButton.java:222)
at androidx.appcompat.widget.SwitchCompat.setChecked(SwitchCompat.java:1183)
at org.gnucash.android.ui.transaction.TransactionFormFragment.initializeViewsWithTransaction(TransactionFormFragment.java:477)
at org.gnucash.android.ui.transaction.TransactionFormFragment.onActivityCreated(TransactionFormFragment.java:380)
at …
```

Calculator error parsing amount string.

---

app/build.gradle
app/src/main/java/org/gnucash/android/ui/report/BaseReportFragment.java
app/src/main/java/org/gnucash/android/ui/report/barchart/StackedBarChartFragment.java
app/src/main/java/org/gnucash/android/ui/report/linechart/CashFlowLineChartFragment.java
app/src/main/java/org/gnucash/android/ui/report/piechart/PieChartFragment.java
app/src/main/kotlin/org/gnucash/android/model/Budget.kt
app/src/main/kotlin/org/gnucash/android/model/BudgetAmount.kt

```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
at com.github.mikephil.charting.highlight.BarHighlighter.getClosestStackIndex(BarHighlighter.java:136)
at com.github.mikephil.charting.highlight.BarHighlighter.getStackedHighlight(BarHighlighter.java:106)
at com.github.mikephil.charting.highlight.BarHighlighter.getHighlight(BarHighlighter.java:37)
at com.github.mikephil.charting.charts.BarChart.getHighlightByTouchPoint(BarChart.java:99)
at com.github.mikephil.charting.charts.BarLineChartBase.getDataSetByTouchPoint(BarLineChartBase.java:1170)
at com.github.mikephil.charting.listener.BarLineChartTouchListener.saveTouchStart(BarLineChartTouchListener.java:239)
at com.github.mikephil.charting.listener.BarLineChartTouchListener.onTouch(BarLineChartTouchListener.ja …
```

Issue with no bar highlight

---

README.md

After this [MR](https://github.com/GnuCash-Pocket/gnucash-android/pull/41) the minimum android version and SDK should be updated.

Update Min Version and SDK in README file

---

app/src/main/java/org/gnucash/android/ui/account/AccountsActivity.java
app/src/main/java/org/gnucash/android/ui/account/AccountsListFragment.java
app/src/main/java/org/gnucash/android/ui/account/DeleteAccountDialogFragment.java
app/src/main/java/org/gnucash/android/ui/settings/BackupPreferenceFragment.java
app/src/main/java/org/gnucash/android/ui/settings/dialog/DeleteAllAccountsConfirmationDialog.java
app/src/main/java/org/gnucash/android/ui/settings/dialog/DeleteAllTransactionsConfirmationDialog.java
app/src/main/java/org/gnucash/android/ui/settings/dialog/DeleteBookConfirmationDialog.java
app/src/main/java/org/gnucash/android/ui/transaction/TransactionsListFragment.java
app/src/main/java/org/gnucash/android/util/BackupManager.java

```
main (native):tid=1 systid=2119 
#00 pc 0xb6688 libc.so (pread + 8) (BuildId: 33ad5959e2b38fc822cda3c642e16c94)
#01 pc 0x121df0 libsqlite.so (unixRead  + 80) (BuildId: e60c0b7514c404e3c68c88612f011391)
#02 pc 0x125208 libsqlite.so (getPageNormal  + 632) (BuildId: e60c0b7514c404e3c68c88612f011391)
#03 pc 0xc4f58 libsqlite.so (btreeNext  + 1080) (BuildId: e60c0b7514c404e3c68c88612f011391)
#04 pc 0xaebac libsqlite.so (sqlite3VdbeExec  + 4556) (BuildId: e60c0b7514c404e3c68c88612f011391)
#05 pc 0xa904c libsqlite.so (sqlite3_step + 124) (BuildId: e60c0b7514c404e3c68c88612f011391)
#06 pc 0x13f094 libandroid_runtime.so (android::nativeExecuteForCursorWindow + 292) (BuildId: 20acab87c40d2d1a61e65371000886ea)
at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native …
```

Backup book async

---

app/src/main/java/org/gnucash/android/db/adapter/BooksDbAdapter.java
app/src/main/java/org/gnucash/android/db/adapter/ScheduledActionDbAdapter.java
app/src/main/java/org/gnucash/android/db/adapter/TransactionsDbAdapter.java
app/src/main/java/org/gnucash/android/export/ExportAsyncTask.java
app/src/main/java/org/gnucash/android/export/csv/CsvTransactionsExporter.java
app/src/main/java/org/gnucash/android/export/xml/GncXmlExporter.java
app/src/main/java/org/gnucash/android/importer/GncXmlHandler.java
app/src/main/java/org/gnucash/android/ui/report/ReportType.java
app/src/main/java/org/gnucash/android/ui/report/sheet/BalanceSheetFragment.java
app/src/test/java/org/gnucash/android/test/unit/export/OfxExporterTest.java
app/src/test/java/org/gnucash/android/test/unit/export/QifExporterTest.java
app/src/test/java/org/gnucash/android/test/unit/importer/GncXmlHandlerTest.java

`A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.`

Close resources

---

app/src/main/java/org/gnucash/android/ui/transaction/TransactionFormFragment.java
app/src/main/java/org/gnucash/android/ui/util/widget/CalculatorEditText.java
app/src/main/kotlin/org/gnucash/android/model/Money.kt
app/src/test/java/org/gnucash/android/test/unit/model/MoneyTest.java

```
Fatal Exception: java.lang.ArithmeticException: Overflow
at java.math.BigDecimal.longValueExact(BigDecimal.java:3643)
at org.gnucash.android.model.Money.getNumerator(Money.kt:145)
at org.gnucash.android.db.adapter.SplitsDbAdapter.setBindings(SplitsDbAdapter.java:107)
at org.gnucash.android.db.adapter.SplitsDbAdapter.setBindings(SplitsDbAdapter.java:53)
at org.gnucash.android.db.adapter.DatabaseAdapter.addRecord(DatabaseAdapter.java:239)
at org.gnucash.android.db.adapter.SplitsDbAdapter.addRecord(SplitsDbAdapter.java:88)
at org.gnucash.android.db.adapter.TransactionsDbAdapter.addRecord(TransactionsDbAdapter.java:124)
at org.gnucash.android.ui.transaction.TransactionFormFragment.saveNewTransaction(TransactionFormFragment.java:875)
at …
```

Money overflow

---

app/src/main/java/org/gnucash/android/ui/util/widget/CalculatorEditText.java
app/src/main/java/org/gnucash/android/ui/util/widget/CalculatorKeyboard.java
app/src/main/res/layout/item_split_entry.xml

and revert split debug colours

Amount edit text focusable.

---

app/src/main/java/org/gnucash/android/db/adapter/CommoditiesDbAdapter.java
app/src/main/java/org/gnucash/android/receivers/AccountCreator.java
app/src/main/java/org/gnucash/android/receivers/TransactionRecorder.java
app/src/main/java/org/gnucash/android/ui/common/FormActivity.java
app/src/main/kotlin/org/gnucash/android/model/Account.kt
app/src/main/kotlin/org/gnucash/android/model/Commodity.kt
app/src/main/kotlin/org/gnucash/android/model/Money.kt
app/src/main/kotlin/org/gnucash/android/model/Transaction.kt

Intent arguments should not be bull.

---

app/src/androidTest/java/org/gnucash/android/test/ui/TransactionsActivityTest.java
app/src/main/java/org/gnucash/android/export/ExportAsyncTask.java
app/src/main/java/org/gnucash/android/export/Exporter.java
app/src/main/java/org/gnucash/android/export/csv/CsvTransactionsExporter.java
app/src/main/java/org/gnucash/android/export/ofx/OfxHelper.java
app/src/main/java/org/gnucash/android/export/qif/QifHelper.java
app/src/main/java/org/gnucash/android/export/xml/GncXmlExporter.java
app/src/main/java/org/gnucash/android/export/xml/GncXmlHelper.java
app/src/main/java/org/gnucash/android/importer/GncXmlHandler.java
app/src/main/java/org/gnucash/android/service/ScheduledActionService.java
app/src/main/java/org/gnucash/android/ui/budget/BudgetFormFragment.java
app/src/main/java/org/gnucash/android/ui/export/ExportFormFragment.java
app/src/main/java/org/gnucash/android/ui/report/ReportsActivity.java
app/src/main/java/org/gnucash/android/ui/settings/BackupPreferenceFragment.java
app/src/main/java/org/gnucash/android/ui/transaction/ScheduledActionsListFragment.java
app/src/main/java/org/gnucash/android/ui/transaction/TransactionDetailActivity.java
app/src/main/java/org/gnucash/android/ui/transaction/TransactionFormFragment.java
app/src/main/java/org/gnucash/android/ui/transaction/TransactionsActivity.java
app/src/main/java/org/gnucash/android/ui/util/dialog/DateRangePickerDialogFragment.java
app/src/main/java/org/gnucash/android/util/TimestampHelper.java
app/src/main/kotlin/org/gnucash/android/model/PeriodType.kt
app/src/main/kotlin/org/gnucash/android/model/Recurrence.kt
app/src/main/kotlin/org/gnucash/android/model/ScheduledAction.kt
app/src/main/kotlin/org/gnucash/android/model/Transaction.kt
app/src/test/java/org/gnucash/android/test/unit/export/GncXmlHelperTest.java
app/src/test/java/org/gnucash/android/test/unit/export/OfxExporterTest.java
app/src/test/java/org/gnucash/android/test/unit/importer/GncXmlHandlerTest.java

Synchronized date-time formatter.

---

app/src/main/java/org/gnucash/android/export/ofx/OfxExporter.java
app/src/main/java/org/gnucash/android/export/qif/QifExporter.java
app/src/main/java/org/gnucash/android/export/xml/GncXmlExporter.java

Export of XML was hanging on some devices (first sort on indexed column).

Export of XML was hanging on some devices

---

app/src/main/java/org/gnucash/android/app/GnuCashApplication.java
app/src/main/java/org/gnucash/android/ui/settings/BackupPreferenceFragment.java
app/src/main/java/org/gnucash/android/ui/settings/TransactionsPreferenceFragment.java
app/src/main/java/org/gnucash/android/ui/settings/dialog/DeleteAllTransactionsConfirmationDialog.java
app/src/main/java/org/gnucash/android/ui/settings/dialog/OwnCloudDialogFragment.java
app/src/main/java/org/gnucash/android/ui/transaction/TransactionsListFragment.java
app/src/main/java/org/gnucash/android/util/BackupManager.java
app/src/main/res/values/donottranslate.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/fragment_about_preferences.xml
app/src/main/res/xml/fragment_backup_preferences.xml

Allow user the option (in Backup Settings) to backup active book before deleting transaction(s).

Backup book before delete transaction?

---

app/src/main/java/org/gnucash/android/ui/account/AccountFormFragment.java
app/src/main/java/org/gnucash/android/ui/account/AccountsActivity.java
app/src/main/java/org/gnucash/android/ui/account/AccountsListFragment.java
app/src/main/java/org/gnucash/android/ui/budget/BudgetAmountEditorFragment.java
app/src/main/java/org/gnucash/android/ui/budget/BudgetDetailFragment.java
app/src/main/java/org/gnucash/android/ui/budget/BudgetFormFragment.java
app/src/main/java/org/gnucash/android/ui/common/BaseDrawerActivity.java
app/src/main/java/org/gnucash/android/ui/common/FormActivity.java
app/src/main/java/org/gnucash/android/ui/export/ExportFormFragment.java
app/src/main/java/org/gnucash/android/ui/report/BaseReportFragment.java
app/src/main/java/org/gnucash/android/ui/report/ReportsActivity.java
app/src/main/java/org/gnucash/android/ui/report/ReportsOverviewFragment.java
app/src/main/java/org/gnucash/android/ui/report/barchart/StackedBarChartFragment.java
app/src/main/java/org/gnucash/android/ui/report/linechart/CashFlowLineChartFragment.java
app/src/main/java/org/gnucash/android/ui/report/piechart/PieChartFragment.java
app/src/main/java/org/gnucash/android/ui/report/sheet/BalanceSheetFragment.java
app/src/main/java/org/gnucash/android/ui/settings/BookManagerFragment.java
app/src/main/java/org/gnucash/android/ui/settings/PreferenceActivity.java
app/src/main/java/org/gnucash/android/ui/transaction/ScheduledActionsListFragment.java
app/src/main/java/org/gnucash/android/ui/transaction/SplitEditorFragment.java
app/src/main/java/org/gnucash/android/ui/transaction/TransactionDetailActivity.java
app/src/main/java/org/gnucash/android/ui/transaction/TransactionFormFragment.java
app/src/main/java/org/gnucash/android/ui/transaction/TransactionsActivity.java
app/src/main/java/org/gnucash/android/ui/transaction/TransactionsListFragment.java
app/src/main/java/org/gnucash/android/util/ContentExt.kt
app/src/main/res/drawable/ic_save_black.xml
app/src/main/res/drawable/ic_save_white.xml
app/src/main/res/drawable/ic_upload_file_black.xml
app/src/main/res/drawable/ic_upload_file_white.xml
app/src/main/res/menu/export_actions.xml

Export form was sometimes appearing multiple times.

Export - singleton form, file name, action icon.

---

app/build.gradle
app/src/main/java/org/gnucash/android/export/xml/GncXmlExporter.java
app/src/main/java/org/gnucash/android/ui/transaction/SplitEditorFragment.java
app/src/main/java/org/gnucash/android/ui/transaction/TransactionFormFragment.java
app/src/main/java/org/gnucash/android/ui/transaction/dialog/TransferFundsDialogFragment.java
app/src/main/java/org/gnucash/android/ui/util/widget/CalculatorEditText.java
app/src/main/java/org/gnucash/android/util/AmountParser.java
app/src/main/kotlin/org/gnucash/android/model/Account.kt
app/src/main/kotlin/org/gnucash/android/model/BudgetAmount.kt
app/src/main/kotlin/org/gnucash/android/model/Commodity.kt
app/src/main/kotlin/org/gnucash/android/model/Money.kt
app/src/main/kotlin/org/gnucash/android/model/Split.kt
app/src/main/kotlin/org/gnucash/android/model/Transaction.kt
app/src/test/java/org/gnucash/android/test/unit/model/MoneyTest.java

Try avoid rounding error when input money.
First merge https://github.com/GnuCash-Pocket/gnucash-android/pull/92

Money is big decimal

---

app/src/main/java/org/gnucash/android/export/ExportAsyncTask.java
app/src/main/java/org/gnucash/android/util/ContentExt.kt

Permission denied for document name?

---

app/src/main/java/org/gnucash/android/ui/account/AccountsListFragment.java
app/src/main/java/org/gnucash/android/ui/export/ExportFormFragment.java
app/src/main/java/org/gnucash/android/ui/settings/BookManagerFragment.java
app/src/main/java/org/gnucash/android/ui/settings/dialog/DeleteBookConfirmationDialog.java

Parent fragment managers preferred for dialogs.

---

app/src/main/java/org/gnucash/android/export/csv/CsvAccountExporter.java
app/src/main/java/org/gnucash/android/export/csv/CsvTransactionsExporter.java
app/src/main/java/org/gnucash/android/export/xml/GncXmlExporter.java
app/src/main/java/org/gnucash/android/ui/account/AccountsActivity.java
app/src/main/java/org/gnucash/android/ui/account/AccountsListFragment.java
app/src/main/java/org/gnucash/android/ui/account/DeleteAccountDialogFragment.java
app/src/main/java/org/gnucash/android/ui/budget/BudgetListFragment.java
app/src/main/java/org/gnucash/android/ui/common/BaseDrawerActivity.java
app/src/main/java/org/gnucash/android/ui/settings/AccountPreferencesFragment.java
app/src/main/java/org/gnucash/android/ui/settings/BookManagerFragment.java
app/src/main/java/org/gnucash/android/ui/settings/dialog/DeleteAllAccountsConfirmationDialog.java
app/src/main/java/org/gnucash/android/ui/settings/dialog/DeleteAllTransactionsConfirmationDialog.java
app/src/main/java/org/gnucash/android/ui/settings/dialog/DeleteBookConfirmationDialog.java
app/src/main/java/org/gnucash/android/ui/settings/dialog/DoubleConfirmationDialog.java
app/src/main/java/org/gnucash/android/ui/transaction/ScheduledActionsListFragment.java
app/src/main/java/org/gnucash/android/ui/transaction/TransactionsActivity.java
app/src/main/java/org/gnucash/android/ui/transaction/TransactionsListFragment.java
app/src/main/java/org/gnucash/android/ui/transaction/dialog/TransactionsDeleteConfirmationDialogFragment.java
app/src/main/java/org/gnucash/android/ui/util/AccountBalanceTask.java
app/src/main/java/org/gnucash/android/ui/wizard/FirstRunWizardActivity.java
app/src/main/java/org/gnucash/android/util/BackupManager.java
app/src/main/java/org/gnucash/android/util/ContentExt.kt
app/src/main/res/drawable/ic_sync_black.xml
app/src/main/res/drawable/ic_sync_white.xml
app/src/main/res/layout/dialog_account_delete.xml
app/src/main/res/layout/dialog_double_confirm.xml
app/src/main/res/layout/radio_group_delete_or_move.xml
app/src/main/res/menu/book_context_menu.xml

Fixes issue #101  and other changes, e.g.:
```
main (native):tid=1 systid=10698 
#00 pc 0x72440 libsqlite.so (sqlite3VdbeExec + 33920) (BuildId: dbd2f8cdeb38269a963f51d2a081f910)
#01 pc 0x35c30 libsqlite.so (sqlite3_step + 464) (BuildId: dbd2f8cdeb38269a963f51d2a081f910)
#02 pc 0x1474a8 libandroid_runtime.so (android::nativeExecuteForCursorWindow + 296) (BuildId: 4ddf5c93d6182fda25302178acf7b932)
at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native method)
at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:1038)
at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
at …
```

Export file name and action icon.

---

app/src/main/java/org/gnucash/android/export/ExportAsyncTask.java
app/src/main/java/org/gnucash/android/ui/settings/BackupPreferenceFragment.java
app/src/main/java/org/gnucash/android/ui/settings/PreferenceActivity.java
app/src/main/java/org/gnucash/android/util/BackupManager.java

When the activity configuration is changed.

---

.github/workflows/nightly-build.yml

unpin test-summary action version as issue is resolved

---

app/src/main/java/org/gnucash/android/ui/util/widget/CalculatorEditText.java
app/src/main/res/layout/item_budget_amount.xml
app/src/main/res/layout/item_split_entry.xml

Split entry bottom margin was chopping amount at top.

---

app/src/main/java/org/gnucash/android/db/DatabaseHelper.java
app/src/main/java/org/gnucash/android/db/adapter/CommoditiesDbAdapter.java
app/src/main/java/org/gnucash/android/importer/CommoditiesXmlHandler.java

avoid inital error messages "Commodity not found in the database: "

Load common commodities when ready.

---

app/src/test/java/org/gnucash/android/test/unit/CsvTransactionsExporterTest.kt
app/src/test/java/org/gnucash/android/test/unit/export/OfxExporterTest.java
app/src/test/resources/multipleTransactionImport.xml

Also a minor change to OfxExporterTest.

Add a test for CsvTransactionsExporter

---

app/src/main/java/org/gnucash/android/db/adapter/BooksDbAdapter.java
app/src/main/java/org/gnucash/android/importer/GncXmlHandler.java
app/src/main/java/org/gnucash/android/importer/GncXmlImporter.java
app/src/main/java/org/gnucash/android/importer/ImportAsyncTask.java
app/src/main/java/org/gnucash/android/util/ContentExt.kt
app/src/test/java/org/gnucash/android/test/unit/BookHelperTest.java

Permission to read imported file name?

---

app/src/main/java/org/gnucash/android/app/GnuCashApplication.java
app/src/main/java/org/gnucash/android/db/adapter/BooksDbAdapter.java

Poor attempt to avoid issue #167

At least 1 book must be available

---

app/src/main/java/org/gnucash/android/ui/account/AccountsListFragment.java
app/src/main/java/org/gnucash/android/ui/budget/BudgetAmountEditorFragment.java
app/src/main/java/org/gnucash/android/ui/budget/BudgetDetailFragment.java
app/src/main/java/org/gnucash/android/ui/budget/BudgetListFragment.java
app/src/main/java/org/gnucash/android/ui/report/BaseReportFragment.java
app/src/main/java/org/gnucash/android/ui/transaction/SplitEditorFragment.java
app/src/main/java/org/gnucash/android/ui/transaction/TransactionDetailActivity.java
app/src/main/java/org/gnucash/android/ui/transaction/TransactionsListFragment.java

I'm currently using the build off this branch, and it works fine, although I cannot guarantee that I've tested all the possible corner cases.
The changes are mostly mechanical, however in some cases (e.g. BaseDrawerActivity and BaseReportFragment) there were changes introduced in how subclasses interact with the base class.
Fixes #73

Migrate from Butterknife to View bindings

---

app/src/androidTest/java/org/gnucash/android/test/ui/PieChartReportTest.java
app/src/main/java/org/gnucash/android/db/DatabaseHelper.java
app/src/main/java/org/gnucash/android/db/DatabaseSchema.java
app/src/main/java/org/gnucash/android/db/MigrationHelper.java
app/src/main/java/org/gnucash/android/db/adapter/AccountsDbAdapter.java
app/src/main/java/org/gnucash/android/db/adapter/CommoditiesDbAdapter.java
app/src/main/java/org/gnucash/android/db/adapter/PricesDbAdapter.java
app/src/main/java/org/gnucash/android/db/adapter/SplitsDbAdapter.java
app/src/main/java/org/gnucash/android/export/ExportAsyncTask.java
app/src/main/java/org/gnucash/android/export/csv/CsvAccountExporter.java
app/src/main/java/org/gnucash/android/export/csv/CsvTransactionsExporter.kt
app/src/main/java/org/gnucash/android/export/xml/GncXmlExporter.java
app/src/main/java/org/gnucash/android/export/xml/GncXmlHelper.java
app/src/main/java/org/gnucash/android/importer/CommoditiesXmlHandler.java
app/src/main/java/org/gnucash/android/importer/GncXmlHandler.java
app/src/main/java/org/gnucash/android/importer/ImportAsyncTask.java
app/src/main/java/org/gnucash/android/util/ConsoleTree.kt
app/src/main/kotlin/org/gnucash/android/model/Account.kt
app/src/main/kotlin/org/gnucash/android/model/Budget.kt
app/src/main/kotlin/org/gnucash/android/model/Commodity.kt
app/src/main/kotlin/org/gnucash/android/model/Money.kt
app/src/main/kotlin/org/gnucash/android/model/Recurrence.kt
app/src/main/kotlin/org/gnucash/android/model/Transaction.kt
app/src/test/java/org/gnucash/android/test/unit/BookHelperTest.java
app/src/test/java/org/gnucash/android/test/unit/importer/GncXmlHandlerTest.java
app/src/test/resources/commodities.xml

Commodities are not only currencies.

---

app/src/main/java/org/gnucash/android/ui/report/ReportType.java

(cherry picked from commit 8fc05755ee7c3a59d008794912e86c705ae81c8f)

Line chart label.

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/gnucash/android/service/ScheduledActionService.java

Try to avoid "Out Of Memory" errors.

---

app/src/main/java/org/gnucash/android/ui/account/AccountsListFragment.java
app/src/main/java/org/gnucash/android/ui/common/UxArgument.java
app/src/main/java/org/gnucash/android/ui/transaction/TransactionDetailActivity.java
app/src/main/java/org/gnucash/android/ui/transaction/TransactionsListFragment.java
app/src/main/java/org/gnucash/android/ui/transaction/dialog/BulkMoveDialogFragment.java
app/src/main/res/layout/activity_transaction_detail.xml
app/src/main/res/menu/transactions_context_menu.xml

Action menu in details screens.

---

app/src/androidTest/java/org/gnucash/android/test/ui/AccountsActivityTest.java
app/src/main/java/org/gnucash/android/app/GnuCashApplication.java
app/src/main/java/org/gnucash/android/db/adapter/AccountsDbAdapter.java
app/src/main/java/org/gnucash/android/db/adapter/CommoditiesDbAdapter.java
app/src/main/java/org/gnucash/android/receivers/AccountCreator.java
app/src/main/java/org/gnucash/android/receivers/TransactionRecorder.java
app/src/main/java/org/gnucash/android/ui/account/AccountFormFragment.java
app/src/main/java/org/gnucash/android/ui/settings/AccountPreferencesFragment.java
app/src/main/kotlin/org/gnucash/android/model/Account.kt
app/src/main/kotlin/org/gnucash/android/model/Commodity.kt
app/src/main/kotlin/org/gnucash/android/model/Money.kt
app/src/test/java/org/gnucash/android/test/unit/CsvTransactionsExporterTest.kt
app/src/test/java/org/gnucash/android/test/unit/db/BudgetsDbAdapterTest.java
app/src/test/java/org/gnucash/android/test/unit/db/TransactionsDbAdapterTest.java
app/src/test/java/org/gnucash/android/test/unit/model/AccountTest.java

Nullable commodity

---

app/src/main/java/org/gnucash/android/app/GnuCashApplication.java
app/src/main/java/org/gnucash/android/ui/common/BaseDrawerActivity.java
app/src/main/java/org/gnucash/android/ui/common/UxArgument.java
app/src/main/java/org/gnucash/android/ui/export/ExportFormFragment.java
app/src/main/java/org/gnucash/android/ui/homescreen/WidgetConfigurationActivity.java
app/src/main/java/org/gnucash/android/ui/passcode/KeyboardFragment.java
app/src/main/java/org/gnucash/android/ui/passcode/PasscodeFragment.kt
app/src/main/java/org/gnucash/android/ui/passcode/PasscodeHelper.kt
app/src/main/java/org/gnucash/android/ui/passcode/PasscodeLockActivity.java
app/src/main/java/org/gnucash/android/ui/passcode/PasscodeLockScreenActivity.java
app/src/main/java/org/gnucash/android/ui/passcode/PasscodeModifyFragment.kt
app/src/main/java/org/gnucash/android/ui/passcode/PasscodePreferenceActivity.java
app/src/main/java/org/gnucash/android/ui/settings/AccountPreferencesFragment.java
app/src/main/java/org/gnucash/android/ui/settings/BackupPreferenceFragment.java
app/src/main/java/org/gnucash/android/ui/settings/BookManagerFragment.java
app/src/main/java/org/gnucash/android/ui/settings/GeneralPreferenceFragment.java
app/src/main/java/org/gnucash/android/ui/settings/TransactionsPreferenceFragment.java
app/src/main/java/org/gnucash/android/util/PreferencesHelper.java
app/src/main/res/layout/passcode_lockscreen.xml
app/src/main/res/xml/fragment_general_preferences.xml

I don't like activities having to listen to fragments.

Passcode fragment and preferences

---

app/src/main/java/org/gnucash/android/app/ContextExt.kt
app/src/main/java/org/gnucash/android/ui/account/AccountFormFragment.java
app/src/main/java/org/gnucash/android/ui/budget/BudgetAmountEditorFragment.java
app/src/main/java/org/gnucash/android/ui/budget/BudgetFormFragment.java
app/src/main/java/org/gnucash/android/ui/common/FormActivity.java
app/src/main/java/org/gnucash/android/ui/transaction/SplitEditorFragment.java
app/src/main/java/org/gnucash/android/ui/transaction/TransactionFormFragment.java
app/src/main/java/org/gnucash/android/ui/util/widget/CalculatorEditText.java
app/src/main/java/org/gnucash/android/ui/util/widget/CalculatorKeyboard.java
app/src/main/java/org/gnucash/android/ui/util/widget/ViewExt.kt
app/src/main/res/layout/dialog_transfer_funds.xml
app/src/main/res/layout/fragment_budget_amount_editor.xml
app/src/main/res/layout/fragment_budget_form.xml
app/src/main/res/layout/fragment_split_editor.xml
app/src/main/res/layout/fragment_transaction_form.xml
app/src/main/res/layout/item_budget_amount.xml
app/src/main/res/layout/item_split_entry.xml
app/src/main/res/layout/kbd_calculator.xml
app/src/main/res/values/attrs.xml
app/src/main/res/xml-land/calculator_keyboard.xml
app/src/main/res/xml/calculator_keyboard.xml
app/src/test/java/org/gnucash/android/test/unit/util/AmountParserTest.java

- Restore calculator keyboard for transaction form.
- Add parentheses to calculator keyboard.
- Fixes issue #175

Calculator keyboard.

---

app/src/main/res/layout/kbd_calculator.xml

Dark theme compatibility.

---

app/build.gradle
app/src/main/java/org/gnucash/android/export/ExportFormat.kt
app/src/main/java/org/gnucash/android/export/csv/CsvTransactionsExporter.kt
app/src/test/java/org/gnucash/android/test/unit/CsvTransactionsExporterTest.kt
app/src/test/java/org/gnucash/android/test/unit/util/AmountParserTest.java

Project does not need to be dependent on Google/Firebase project.

No Google json

---

app/src/main/java/org/gnucash/android/ui/account/AccountsActivity.java
app/src/main/java/org/gnucash/android/ui/budget/BudgetAmountEditorFragment.java
app/src/main/java/org/gnucash/android/ui/budget/BudgetFormFragment.java
app/src/main/java/org/gnucash/android/ui/transaction/SplitEditorFragment.java
app/src/main/java/org/gnucash/android/ui/transaction/TransactionFormFragment.java
app/src/main/java/org/gnucash/android/ui/util/widget/CalculatorEditText.java
app/src/main/java/org/gnucash/android/ui/util/widget/CalculatorKeyboard.java

Hide other soft keyboards for calculator editor when refocused.

---

app/src/main/java/org/gnucash/android/db/DatabaseSchema.java
app/src/main/java/org/gnucash/android/db/adapter/BooksDbAdapter.java
app/src/main/java/org/gnucash/android/db/adapter/BudgetAmountsDbAdapter.java
app/src/main/java/org/gnucash/android/db/adapter/BudgetsDbAdapter.java
app/src/main/java/org/gnucash/android/db/adapter/CommoditiesDbAdapter.java
app/src/main/java/org/gnucash/android/db/adapter/DatabaseAdapter.java
app/src/main/java/org/gnucash/android/db/adapter/PricesDbAdapter.java
app/src/main/java/org/gnucash/android/db/adapter/RecurrenceDbAdapter.java
app/src/main/java/org/gnucash/android/db/adapter/SplitsDbAdapter.java
app/src/main/java/org/gnucash/android/ui/transaction/SplitEditorFragment.java
app/src/main/kotlin/org/gnucash/android/model/Account.kt
app/src/main/kotlin/org/gnucash/android/model/BaseModel.kt
app/src/main/kotlin/org/gnucash/android/model/Commodity.kt

Beginning of fixing issue #201

Sometimes sort accounts with favorites first.

---

app/src/main/java/org/gnucash/android/app/MenuFragment.kt
app/src/main/java/org/gnucash/android/ui/account/AccountFormFragment.java
app/src/main/java/org/gnucash/android/ui/account/AccountsListFragment.java
app/src/main/java/org/gnucash/android/ui/budget/BudgetAmountEditorFragment.java
app/src/main/java/org/gnucash/android/ui/budget/BudgetDetailFragment.java
app/src/main/java/org/gnucash/android/ui/budget/BudgetFormFragment.java
app/src/main/java/org/gnucash/android/ui/budget/BudgetListFragment.java
app/src/main/java/org/gnucash/android/ui/export/ExportFormFragment.java
app/src/main/java/org/gnucash/android/ui/report/BaseReportFragment.java
app/src/main/java/org/gnucash/android/ui/settings/AboutPreferenceFragment.java
app/src/main/java/org/gnucash/android/ui/settings/AccountPreferencesFragment.java
app/src/main/java/org/gnucash/android/ui/settings/BackupPreferenceFragment.java
app/src/main/java/org/gnucash/android/ui/settings/BookManagerFragment.java
app/src/main/java/org/gnucash/android/ui/settings/GeneralPreferenceFragment.java
app/src/main/java/org/gnucash/android/ui/settings/PreferenceActivity.java
app/src/main/java/org/gnucash/android/ui/settings/TransactionsPreferenceFragment.java
app/src/main/java/org/gnucash/android/ui/transaction/ScheduledActionsListFragment.java
app/src/main/java/org/gnucash/android/ui/transaction/SplitEditorFragment.java
app/src/main/java/org/gnucash/android/ui/transaction/TransactionFormFragment.java
app/src/main/java/org/gnucash/android/ui/transaction/TransactionsListFragment.java
app/src/main/res/menu/account_actions.xml
app/src/main/res/menu/global_actions.xml

Menu provider.

---

app/src/main/java/org/gnucash/android/db/adapter/ScheduledActionDbAdapter.java
app/src/main/java/org/gnucash/android/db/adapter/SplitsDbAdapter.java

Timestamp should be UTC

---

app/build.gradle
app/src/main/java/org/gnucash/android/ui/util/widget/FragmentViewHolder.kt

```
Fatal Exception: java.lang.IllegalStateException: Fragment already added: ReviewFragment{527f6de} (1b503f88-9b1e-43c1-9a0b-4dcd41d653af tag=f0)
at androidx.fragment.app.FragmentStore.addFragment(FragmentStore.java:92)
at androidx.fragment.app.FragmentManager.addFragment(FragmentManager.java:1481)
at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:387)
at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:1965)
at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1873)
at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1729)
at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLo …
```

Crashlytics issue f531b71f9d4fcb7f46a1279350f571f1

---

app/src/main/java/org/gnucash/android/ui/account/AccountFormFragment.java
app/src/main/java/org/gnucash/android/ui/budget/BudgetDetailFragment.java
app/src/main/java/org/gnucash/android/ui/export/ExportFormFragment.java
app/src/main/java/org/gnucash/android/ui/report/ReportsActivity.java
app/src/main/java/org/gnucash/android/ui/settings/BookManagerFragment.java
app/src/main/java/org/gnucash/android/ui/settings/PreferenceActivity.java
app/src/main/java/org/gnucash/android/ui/transaction/ScheduledActionsListFragment.java
app/src/main/java/org/gnucash/android/ui/transaction/SplitEditorFragment.java
app/src/main/java/org/gnucash/android/ui/transaction/TransactionFormFragment.java

```
Fatal Exception: java.lang.IllegalStateException: Fragment TransactionFormFragment{ef476a5} (4d0e0a8d-4e75-4528-8d1c-940448021690) not attached to a context.
at androidx.fragment.app.Fragment.requireContext(Fragment.java:967)
at org.gnucash.android.ui.transaction.TransactionFormFragment.onOptionsItemSelected(TransactionFormFragment.java:931)
at org.gnucash.android.app.MenuFragment$onCreate$1.onMenuItemSelected(MenuFragment.kt:23)
at androidx.core.view.MenuHostHelper.onMenuItemSelected(MenuHostHelper.java:107)
at androidx.activity.ComponentActivity.onMenuItemSelected(ComponentActivity.java:532)
at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:265)
at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:269)
at …
```

Avoid null context in fragments.

---

app/build.gradle
app/src/main/java/org/gnucash/android/export/ExportAsyncTask.java
app/src/main/java/org/gnucash/android/service/ScheduledActionService.java
app/src/main/java/org/gnucash/android/ui/transaction/ScheduledActionsListFragment.java
app/src/main/java/org/gnucash/android/ui/transaction/TransactionDetailActivity.java
app/src/main/java/org/gnucash/android/util/DateExt.kt
app/src/main/kotlin/org/gnucash/android/model/Recurrence.kt

```
Caused by java.lang.IllegalArgumentException: Illegal pattern component: cccc
at org.joda.time.format.DateTimeFormat.parsePatternTo(DateTimeFormat.java:566)
at org.joda.time.format.DateTimeFormat.createFormatterForPattern(DateTimeFormat.java:687)
at org.joda.time.format.DateTimeFormat.forPattern(DateTimeFormat.java:177)
at org.joda.time.format.DateTimeFormat$StyleFormatter.getFormatter(DateTimeFormat.java:833)
at org.joda.time.format.DateTimeFormat$StyleFormatter.printTo(DateTimeFormat.java:810)
at org.joda.time.format.DateTimeFormatter.printTo(DateTimeFormatter.java:738)
at org.joda.time.format.DateTimeFormatter.printTo(DateTimeFormatter.java:595)
at org.joda.time.format.DateTimeFormatter.print(DateTimeFormatter.java:698)
at …
```

Joda date time: Illegal pattern component: cccc

---

app/src/main/java/org/gnucash/android/db/DatabaseHelper.java
app/src/main/java/org/gnucash/android/ui/account/AccountFormFragment.java

```
Fatal Exception: android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY[787])
at android.database.sqlite.SQLiteConnection.nativeExecute(SQLiteConnection.java)
at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:1034)
at android.database.sqlite.SQLiteSession.execute(SQLiteSession.java:621)
at android.database.sqlite.SQLiteStatement.execute(SQLiteStatement.java:47)
at org.gnucash.android.db.adapter.DatabaseAdapter.addRecord(DatabaseAdapter.java:232)
at org.gnucash.android.db.adapter.AccountsDbAdapter.addRecord(AccountsDbAdapter.java:149)
at org.gnucash.android.ui.account.AccountFormFragment.saveAccount(AccountFormFragment.java:687)
at org.gnucash.android.ui.account.AccountFormFragment.onOptionsItemSele …
```

Avoid "FOREIGN KEY constraint failed" for account.

---

app/src/androidTest/java/org/gnucash/android/test/ui/AccountsActivityTest.java
app/src/androidTest/java/org/gnucash/android/test/ui/ExportTransactionsTest.java
app/src/androidTest/java/org/gnucash/android/test/ui/OwnCloudExportTest.java
app/src/main/java/org/gnucash/android/db/BookDbHelper.java
app/src/main/java/org/gnucash/android/db/adapter/AccountsDbAdapter.java
app/src/main/java/org/gnucash/android/db/adapter/BooksDbAdapter.java
app/src/main/java/org/gnucash/android/db/adapter/DatabaseAdapter.java
app/src/main/java/org/gnucash/android/db/adapter/SplitsDbAdapter.java
app/src/main/java/org/gnucash/android/db/adapter/TransactionsDbAdapter.java
app/src/main/java/org/gnucash/android/export/ExportAsyncTask.java
app/src/main/java/org/gnucash/android/importer/GncXmlHandler.java
app/src/main/java/org/gnucash/android/service/ScheduledActionService.java
app/src/main/java/org/gnucash/android/ui/settings/BookManagerFragment.java
app/src/main/java/org/gnucash/android/ui/transaction/TransactionDetailActivity.java
app/src/main/java/org/gnucash/android/ui/transaction/TransactionsListFragment.java
app/src/test/java/org/gnucash/android/service/ScheduledActionServiceTest.java
app/src/test/java/org/gnucash/android/test/unit/BookHelperTest.java
app/src/test/java/org/gnucash/android/test/unit/GnuCashTest.kt
app/src/test/java/org/gnucash/android/test/unit/db/AccountsDbAdapterTest.java
app/src/test/java/org/gnucash/android/test/unit/db/BooksDbAdapterTest.java
app/src/test/java/org/gnucash/android/test/unit/export/BackupTest.java
app/src/test/java/org/gnucash/android/test/unit/export/QifExporterTest.java
app/src/test/java/org/gnucash/android/util/BackupManagerTest.java

`E/TransactionsDbAdapter: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5 SQLITE_BUSY) at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method) at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:744) at android.database.sqlite.SQLiteSession.beginTransactionUnchecked(SQLiteSession.java:325) at android.database.sqlite.SQLiteSession.beginTransaction(SQLiteSession.java:300) at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:740) at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:650) at org.gnucash.android.db.adapter.DatabaseAdapter.beginTransaction(DatabaseAdapter.java:829) at org.gnucash.android.db.adapter.TransactionsDbAdapter.addRecord(TransactionsDbAdapter.java: …

Cannot show transaction details if not added to database.

---

app/src/main/java/org/gnucash/android/db/adapter/AccountsDbAdapter.java
app/src/main/java/org/gnucash/android/db/adapter/BooksDbAdapter.java
app/src/main/java/org/gnucash/android/db/adapter/BudgetAmountsDbAdapter.java
app/src/main/java/org/gnucash/android/db/adapter/BudgetsDbAdapter.java
app/src/main/java/org/gnucash/android/db/adapter/CommoditiesDbAdapter.java
app/src/main/java/org/gnucash/android/db/adapter/DatabaseAdapter.java
app/src/main/java/org/gnucash/android/db/adapter/PricesDbAdapter.java
app/src/main/java/org/gnucash/android/db/adapter/RecurrenceDbAdapter.java
app/src/main/java/org/gnucash/android/db/adapter/ScheduledActionDbAdapter.java
app/src/main/java/org/gnucash/android/db/adapter/SplitsDbAdapter.java
app/src/main/java/org/gnucash/android/db/adapter/TransactionsDbAdapter.java
app/src/main/java/org/gnucash/android/ui/report/BaseReportFragment.java
app/src/main/java/org/gnucash/android/ui/report/ReportsOverviewFragment.java
app/src/main/java/org/gnucash/android/ui/report/barchart/StackedBarChartFragment.java
app/src/main/java/org/gnucash/android/ui/report/piechart/PieChartFragment.java
app/src/main/java/org/gnucash/android/ui/transaction/TransactionDetailActivity.java
app/src/main/res/menu/chart_actions.xml

Ignore accounts with no actual transactions for reports.

---

app/src/main/java/org/gnucash/android/app/GnuCashApplication.java
app/src/main/java/org/gnucash/android/db/adapter/AccountsDbAdapter.java
app/src/main/java/org/gnucash/android/db/adapter/CommoditiesDbAdapter.java
app/src/main/java/org/gnucash/android/db/adapter/PricesDbAdapter.java
app/src/main/java/org/gnucash/android/db/adapter/SplitsDbAdapter.java
app/src/main/java/org/gnucash/android/db/adapter/TransactionsDbAdapter.java
app/src/main/java/org/gnucash/android/export/Exporter.java
app/src/main/java/org/gnucash/android/importer/GncXmlHandler.java
app/src/main/java/org/gnucash/android/ui/settings/AccountPreferencesFragment.java
app/src/main/java/org/gnucash/android/ui/transaction/TransactionFormFragment.java
app/src/main/kotlin/org/gnucash/android/model/Money.kt
app/src/test/java/org/gnucash/android/test/unit/BookHelperTest.java
app/src/test/java/org/gnucash/android/test/unit/db/AccountsDbAdapterTest.java
app/src/test/java/org/gnucash/android/test/unit/model/BudgetTest.java
app/src/test/java/org/gnucash/android/test/unit/model/CommodityTest.java
app/src/test/java/org/gnucash/android/test/unit/model/PriceTest.java
app/src/test/java/org/gnucash/android/test/unit/model/RecurrenceTest.kt
app/src/test/java/org/gnucash/android/test/unit/util/AmountParserTest.java
app/src/test/java/org/gnucash/android/test/unit/util/ColorTest.kt

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.gnucash.android.model.Commodity.getCurrencyCode()' on a null object reference
at org.gnucash.android.app.GnuCashApplication.getDefaultCurrencyCode(GnuCashApplication.java:376)
at org.gnucash.android.db.adapter.CommoditiesDbAdapter.initCommon(CommoditiesDbAdapter.java:66)
at org.gnucash.android.db.adapter.CommoditiesDbAdapter.<init>(CommoditiesDbAdapter.java:50)
at org.gnucash.android.db.adapter.CommoditiesDbAdapter.<init>(CommoditiesDbAdapter.java:29)
at org.gnucash.android.db.adapter.TransactionsDbAdapter.<init>(TransactionsDbAdapter.java:84)
at org.gnucash.android.db.BookDbHelper.insertBlankBook(BookDbHelper.java:81)
at org.gnucash.android.db.BookDbHelper.onCreate(BookDbHelper.java:73) …
```

Default commodity should always be valid.

---

app/src/main/java/org/gnucash/android/inputmethodservice/CalculatorKeyboardView.kt
app/src/main/java/org/gnucash/android/ui/util/widget/CalculatorEditText.java
app/src/main/java/org/gnucash/android/ui/util/widget/CalculatorKeyboard.java

There was a bug where if Android system language is set to Arabic, the app did not allow entering transaction amounts.
I fixed it by adding the Arabic numbers to the ACCEPTED string in CalculatorKeyboard.java

Arabic Data Entry Fix

---

app/src/main/java/org/gnucash/android/ui/account/AccountsListFragment.java
app/src/main/java/org/gnucash/android/ui/transaction/TransactionsListFragment.java
app/src/main/res/layout/cardview_account.xml
app/src/main/res/layout/cardview_transaction.xml
app/src/main/res/menu/transactions_context_menu.xml

Account list item with RTL name

---

app/src/main/java/org/gnucash/android/export/csv/CsvTransactionsExporter.kt
app/src/main/java/org/gnucash/android/ui/transaction/ScheduledExportsListFragment.kt
app/src/main/java/org/gnucash/android/ui/transaction/ScheduledTransactionsListFragment.kt
app/src/main/kotlin/org/gnucash/android/export/ofx/OfxExporter.kt
app/src/main/kotlin/org/gnucash/android/model/Account.kt
app/src/main/kotlin/org/gnucash/android/model/BaseModel.kt
app/src/main/kotlin/org/gnucash/android/model/Budget.kt
app/src/main/kotlin/org/gnucash/android/model/BudgetAmount.kt
app/src/main/kotlin/org/gnucash/android/model/Commodity.kt
app/src/main/kotlin/org/gnucash/android/model/Price.kt
app/src/main/kotlin/org/gnucash/android/model/ScheduledAction.kt
app/src/main/kotlin/org/gnucash/android/model/Split.kt
app/src/main/kotlin/org/gnucash/android/model/Transaction.kt
app/src/test/java/org/gnucash/android/test/unit/model/AccountTest.java

`uID` just seems wrong somehow. Should be either UID or Uid.

UID naming.

---

app/src/main/java/org/gnucash/android/db/adapter/TransactionsDbAdapter.java
app/src/main/java/org/gnucash/android/export/qif/QifExporter.java
app/src/main/java/org/gnucash/android/service/ScheduledActionService.java
app/src/main/kotlin/org/gnucash/android/model/Commodity.kt
app/src/test/java/org/gnucash/android/service/ScheduledActionServiceTest.java

Importing a book marks **all** transactions a modified to now.
Doesn't the user really want to export transactions from a specific transaction date?
Part of issue #98

Export transactions since.

---

app/src/main/java/org/gnucash/android/db/adapter/TransactionsDbAdapter.java
app/src/main/java/org/gnucash/android/export/qif/QifExporter.java
app/src/main/java/org/gnucash/android/export/qif/QifHelper.java
app/src/main/java/org/gnucash/android/export/xml/GncXmlExporter.java
app/src/test/java/org/gnucash/android/test/unit/export/QifExporterTest.java

QIF export splits

---

app/src/main/java/org/gnucash/android/ui/report/BaseReportFragment.java
app/src/main/java/org/gnucash/android/ui/report/ReportType.java
app/src/main/java/org/gnucash/android/ui/report/ReportsOverviewFragment.java
app/src/main/java/org/gnucash/android/ui/report/sheet/BalanceSheetFragment.java

Balance sheet was adding duplicate rows

---

app/src/main/java/org/gnucash/android/ui/account/AccountsActivity.java
app/src/main/java/org/gnucash/android/ui/common/BaseDrawerActivity.java
app/src/main/java/org/gnucash/android/ui/settings/AccountPreferencesFragment.java
app/src/main/java/org/gnucash/android/ui/settings/BookManagerFragment.java
app/src/main/java/org/gnucash/android/ui/wizard/FirstRunWizardActivity.java
app/src/main/java/org/gnucash/android/util/DocumentExt.kt

```
Fatal Exception: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT cat=[android.intent.category.OPENABLE] typ=text/*|application/* (has extras) }
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2087)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1747)
at android.app.Activity.startActivityForResult(Activity.java:5532)
at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:780)
at android.app.Activity.startActivityForResult(Activity.java:5485)
at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:761)
at org.gnucash.android.ui.common.BaseDrawerActivity.onDrawerMenuItemClicked(BaseDrawerActivity.java:274) …
```

Open document or content.

---

app/src/main/java/org/gnucash/android/ui/settings/AboutPreferenceFragment.java
app/src/main/java/org/gnucash/android/ui/settings/AccountPreferencesFragment.java
app/src/main/java/org/gnucash/android/ui/settings/BackupPreferenceFragment.java
app/src/main/java/org/gnucash/android/ui/settings/GeneralPreferenceFragment.java
app/src/main/java/org/gnucash/android/ui/settings/PreferenceHeadersFragment.java
app/src/main/java/org/gnucash/android/ui/settings/TransactionsPreferenceFragment.java

Steps to reproduce:
1. settings > general
2. enable passcode
3. rotate screen
4. rotate screen back
5. press back key
6. expected result - not crash

Passcode rotate

---

app/src/androidTest/java/org/gnucash/android/test/ui/AccountsActivityTest.java
app/src/main/java/org/gnucash/android/db/adapter/AccountsDbAdapter.java
app/src/test/java/org/gnucash/android/test/unit/importer/GncXmlHandlerTest.java

(cherry picked from commit 8ef66074aa5256ac13a65b0ad909428aa6ed7d35)

Root accounts not hidden.

---

app/src/main/java/org/gnucash/android/ui/report/linechart/CashFlowLineChartFragment.java
app/src/main/java/org/gnucash/android/ui/transaction/TransactionFormFragment.java

```
Fatal Exception: java.lang.ArithmeticException: divide by zero
at org.gnucash.android.ui.report.linechart.CashFlowLineChartFragment.onOptionsItemSelected(CashFlowLineChartFragment.java:387)
at org.gnucash.android.app.MenuFragment$onCreate$1.onMenuItemSelected(MenuFragment.kt:31)
at androidx.core.view.MenuHostHelper.onMenuItemSelected(MenuHostHelper.java:107)
at androidx.activity.ComponentActivity.onMenuItemSelected(ComponentActivity.java:532)
at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:265)
at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:269)
at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarAc …
```

Upgrade charting library.

---

app/build.gradle.kts
app/src/androidTest/java/org/gnucash/android/test/ui/TransactionsActivityTest.kt
app/src/main/java/org/gnucash/android/db/adapter/DatabaseAdapter.java
app/src/main/java/org/gnucash/android/db/adapter/PricesDbAdapter.java
app/src/main/java/org/gnucash/android/export/xml/GncXmlExporter.java
app/src/main/java/org/gnucash/android/importer/GncXmlHandler.java
app/src/main/java/org/gnucash/android/quote/QuoteCallback.kt
app/src/main/java/org/gnucash/android/quote/QuoteProvider.kt
app/src/main/java/org/gnucash/android/quote/YahooJson.kt
app/src/main/java/org/gnucash/android/ui/transaction/dialog/TransferFundsDialogFragment.java
app/src/main/kotlin/org/gnucash/android/model/Price.kt
app/src/main/kotlin/org/gnucash/android/model/PriceType.kt
app/src/main/res/layout/dialog_transfer_funds.xml
app/src/main/res/values/donottranslate.xml

https://wiki.gnucash.org/wiki/Online_Quotes
https://github.com/finance-quote/finance-quote/blob/master/lib/Finance/Quote/CurrencyRates/YahooJSON.pm
Partially resolves issue #38

Fetch exchange rate.

---

app/src/main/java/org/gnucash/android/ui/transaction/TransactionFormFragment.java

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.gnucash.android.model.Account.getUID()' on a null object reference
at org.gnucash.android.ui.transaction.TransactionFormFragment.updateTransferAccountsList(TransactionFormFragment.java:544)
at org.gnucash.android.ui.transaction.TransactionFormFragment.onViewCreated(TransactionFormFragment.java:216)
at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3128)
at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:552)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
at …
```

Did account get reset?
